### ISSUE TITLE
How do I support the CPUS_UNLOCK_WORKSTATION scenario?

### ISSUE THREAD

**Issue by DSBloom** [phaetto/windows-credentials-provider#7]
I am using your code and working on a Windows 10 Cred Provider, and I am having trouble with the CPUS_UNLOCK_WORKSTATION scenario. My CP simply serializes a Username and Password and logs the user in. This works in the CPUS_LOGON scenario, but I get a bad username and password in the CPUS_UNLOCK_WORKSTATION scenario. 

According to MS docs (https://docs.microsoft.com/en-us/windows/desktop/api/credentialprovider/ne-credentialprovider-credential_provider_usage_scenario), "Credential providers that implement this scenario should be prepared to serialize credentials to the local authority for authentication. **These credential providers also need to enumerate the currently logged-in user as the default tile**."

How exactly do I do that? I think that the `CredentialProviderBase:SetUserArray` is the place to do it, but I don't know how.

Any insight you can give would be appreciated. Thank you.

**EDIT: ** I also posted this issue in https://github.com/SteveSyfuhs/CredProvider.NET because truthfully I am using code from both repos.

**Comment by DSBloom** [comment]
So I've switched gears a little bit here, and am going to wrap the Windows password provider.

I have so far successfully translated this sample https://github.com/pauldotknopf/WindowsSDK7-Samples/tree/master/security/credentialproviders/samplewrapexistingcredentialprovider to your C# code, but I am kind of confused on how I would wrap the `ICredentialProviderCredential` object.

In the C++ example, there is an initialize method that takes in a 'ICredentialProviderCredential', and then they assign it to their local object like so: `_pWrappedCredential = pWrappedCredential`.

I don't see an initialize method in your `TestWindowsCredentialProviderTile.cs` class, or even in the 'ICredentialProviderCredential' interface here https://docs.microsoft.com/en-us/windows/desktop/api/credentialprovider/nn-credentialprovider-icredentialprovidercredential.

How can I get a reference to the password provider's `ICredentialProviderCredential` and call it from my wrapped credential?

**Comment by phaetto** [comment]
Hi @nadcraker,

IMHO you shouldn't wrap the default credential provider. Unless it's a fun project it could limit you from different OS customisations that you might have to do.

Right now I am pretty sure that the CPUS_UNLOCK_WORKSTATION scenario is not supported.
The problem is the method CredPackAuthenticationBuffer which creates a KERB_INTERACTIVE_UNLOCK_LOGON structure (internally) with MessageType always KerbInteractiveLogon.

The proper C++ implementation in pgina [looks like this](https://github.com/pgina/pgina/blob/f7cf2a074cf00432aa619478cedd8181b31f1680/pGina/src/CredentialProvider/Credential.cpp#L375).

I hope that helps,
Alexander
